### ISSUE TITLE
sandbox returning server errors

### ISSUE THREAD

**Issue by WylieG** [APWG/ecx2-openapi-doc#8]
Hi, I'm trying to test against the sandbox but I just get 500 errors from the server. 
```
POST ..../phish

{
  "value": {
    "url": "http://demolink3.com",
    "brand": "APWG",
    "discoveredAt": 1672275596,
    "status": "inactive",
    "confidence": 50
  }
}
```

```
Error: Internal Server ErrorResponse bodyDownload
{  "type": "api_error",   "code": "internal_server_error",   "message": "Internal Server Error",   "errors": [] }
```

I tried to contact support@ecrimex.net but the email bounced.

https://github.com/APWG/ecx-support leads to a 404 page

**Comment by patcain** [comment]
Hi,
I fixed the support bouncing problem. We’re setting up the new servers and fat-fingered something.
The POST message doesn’t need the “value” object; the phish entry is just a series of the fields:
{
    "url": "http://demolink3.com",
    "brand": "APWG",
    "discoveredAt": 1672275596,
    "status": "inactive",
    "confidence": 50
}
 
Do we have a documentation error somewhere? We have read/edited/reread the docs so much we’re skipping parts.
Sorry about your troubles,
 
Pat
eCX support
 
From: WylieG ***@***.***> 
Sent: Monday, January 8, 2024 8:50 AM
To: APWG/ecx2-openapi-doc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APWG/ecx2-openapi-doc] sandbox returning server errors (Issue #8)
 
Hi, I'm trying to test against the sandbox but I just get 500 errors from the server.
POST ..../phish
 
{
  "value": {
    "url": "http://demolink3.com",
    "brand": "APWG",
    "discoveredAt": 1672275596,
    "status": "inactive",
    "confidence": 50
  }
}
Error: Internal Server ErrorResponse bodyDownload
{  "type": "api_error",   "code": "internal_server_error",   "message": "Internal Server Error",   "errors": [] }
I tried to contact ***@***.*** ***@***.***>  but the email bounced.

**Comment by WylieG** [comment]
Hi Pat, thanks for the quick response. 

The value object came from the swagger documentation I tested it via that as well and got the same error. 


<img width="1091" alt="ecrimex_swagger" src="https://github.com/APWG/ecx2-openapi-doc/assets/18547691/f88dbef0-1027-4b68-b6ef-f21cffd297af">

I tested with:

```
curl -k -X 'POST'   'https://sandbox.ecx2.ecrimex.net/api/v1/phish'  
   -H 'accept: application/json'   
   -H 'Authorization: <my api key>' 
   -H 'Content-Type: application/json'   
   -d '{
      "url": "http://demolink3.com",
      "brand": "APWG",
      "discoveredAt": 1672275596,
      "status": "inactive",
      "confidence": 50
   }'
```
Response:
```
{"type":"api_error","code":"internal_server_error","message":"Internal Server Error","errors":[]}
```

I'm using my  existing api key though I'd expect 400 errors if that were the issue.

**Comment by patcain** [comment]
This was fixed in the software mid-January.
